version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file: .env
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env


  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - django

  redis:
    image: redis:3.0
