# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20171127_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='id',
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Survey ID'),
        ),
    ]
