# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20171128_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='username',
            new_name='user',
        ),
    ]
