# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('users', '0002_user_churchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
