# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acitvesurvey',
            field=models.BooleanField(default=False, verbose_name='Is Survey Active'),
        ),
    ]
