# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_acitvesurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='survey',
        ),
        migrations.AlterField(
            model_name='user',
            name='acitvesurvey',
            field=models.BooleanField(default=True, verbose_name='Is Survey Active'),
        ),
    ]
