# Generated by Django 2.0.4 on 2018-04-19 20:47

from django.db import migrations, models
import django.utils.timezone
import pulsemanager.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hierarchy',
            field=pulsemanager.users.models.HierarchyField(choices=[('MN', 'Main'), ('CD', 'Daughter')], default='MN', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='churchname',
            field=models.CharField(max_length=255, verbose_name='Name of Church'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of User'),
        ),
    ]
